source:              .
destination:         ./_site
plugins_dir:         ./_plugins
layouts_dir:         ./_layouts
include:             ['.htaccess']
exclude:             []
keep_files:          ['.git','.svn']
timezone:            nil

future:              true
show_drafts:         nil
limit_posts:         0
highlighter:         rouge

safe:                false
host:                0.0.0.0
port:                4000
baseurl:     
url:                 http://localhost:4000
lsi:                 false

markdown_ext:        "markdown,mkdown,mkdn,mkd,md"
excerpt_separator:  "\n\n"